# Generated by Django 2.2.6 on 2019-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0002_auto_20191023_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrecord',
            name='MaritalStatus',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Widowed Young', 'Widowed Young'), ('Widowed Old', 'Widowed Old'), ('Divorced', 'Divorced'), ('Married', 'Married')], default='Married', max_length=50, verbose_name='Marital Status'),
            preserve_default=False,
        ),
    ]
