# Generated by Django 2.2.6 on 2019-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0004_auto_20191028_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='MaritalStatus',
            field=models.CharField(choices=[('Never Married', 1.1), ('Widowed Young', 1), ('Widowed Old', 1.2), ('Divorced', 1), ('Married', 0.8)], default='Never Married', max_length=50, verbose_name='Marital Status'),
        ),
    ]
