# Generated by Django 2.2.6 on 2019-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0006_auto_20191028_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='MaritalStatus',
            field=models.CharField(choices=[(1, 'never married'), (1, 'Married')], max_length=50, verbose_name='Marital Status'),
        ),
    ]
