# Generated by Django 2.2.6 on 2019-10-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0007_auto_20191029_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='MaritalStatus',
            field=models.CharField(choices=[(1.1, 'Never Married'), (1, 'Widowed Young'), (1.2, 'Widowed Old'), (1, 'Divorced'), (0.8, 'Married')], max_length=50, verbose_name='Marital Status'),
        ),
    ]
